apiVersion: v2
name: pss-restricted-policies-pri
description: Pod Security Standards (restricted) policy set
type: application
version: 0.4.1-RC1
appVersion: 0.1.0
keywords:
  - kubernetes
  - nirmata
  - kyverno
  - policy
maintainers:
  - name: Nirmata
    url: https://nirmata.com/
